// Generated by gencpp from file pololu_maestro_ros/set_servo.msg
// DO NOT EDIT!


#ifndef POLOLU_MAESTRO_ROS_MESSAGE_SET_SERVO_H
#define POLOLU_MAESTRO_ROS_MESSAGE_SET_SERVO_H

#include <ros/service_traits.h>


#include <pololu_maestro_ros/set_servoRequest.h>
#include <pololu_maestro_ros/set_servoResponse.h>


namespace pololu_maestro_ros
{

struct set_servo
{

typedef set_servoRequest Request;
typedef set_servoResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct set_servo
} // namespace pololu_maestro_ros


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::pololu_maestro_ros::set_servo > {
  static const char* value()
  {
    return "cacdc30924dce4f90463bf4f4695d124";
  }

  static const char* value(const ::pololu_maestro_ros::set_servo&) { return value(); }
};

template<>
struct DataType< ::pololu_maestro_ros::set_servo > {
  static const char* value()
  {
    return "pololu_maestro_ros/set_servo";
  }

  static const char* value(const ::pololu_maestro_ros::set_servo&) { return value(); }
};


// service_traits::MD5Sum< ::pololu_maestro_ros::set_servoRequest> should match
// service_traits::MD5Sum< ::pololu_maestro_ros::set_servo >
template<>
struct MD5Sum< ::pololu_maestro_ros::set_servoRequest>
{
  static const char* value()
  {
    return MD5Sum< ::pololu_maestro_ros::set_servo >::value();
  }
  static const char* value(const ::pololu_maestro_ros::set_servoRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::pololu_maestro_ros::set_servoRequest> should match
// service_traits::DataType< ::pololu_maestro_ros::set_servo >
template<>
struct DataType< ::pololu_maestro_ros::set_servoRequest>
{
  static const char* value()
  {
    return DataType< ::pololu_maestro_ros::set_servo >::value();
  }
  static const char* value(const ::pololu_maestro_ros::set_servoRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::pololu_maestro_ros::set_servoResponse> should match
// service_traits::MD5Sum< ::pololu_maestro_ros::set_servo >
template<>
struct MD5Sum< ::pololu_maestro_ros::set_servoResponse>
{
  static const char* value()
  {
    return MD5Sum< ::pololu_maestro_ros::set_servo >::value();
  }
  static const char* value(const ::pololu_maestro_ros::set_servoResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::pololu_maestro_ros::set_servoResponse> should match
// service_traits::DataType< ::pololu_maestro_ros::set_servo >
template<>
struct DataType< ::pololu_maestro_ros::set_servoResponse>
{
  static const char* value()
  {
    return DataType< ::pololu_maestro_ros::set_servo >::value();
  }
  static const char* value(const ::pololu_maestro_ros::set_servoResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // POLOLU_MAESTRO_ROS_MESSAGE_SET_SERVO_H
