// Generated by gencpp from file pololu_maestro_ros/set_servoResponse.msg
// DO NOT EDIT!


#ifndef POLOLU_MAESTRO_ROS_MESSAGE_SET_SERVORESPONSE_H
#define POLOLU_MAESTRO_ROS_MESSAGE_SET_SERVORESPONSE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace pololu_maestro_ros
{
template <class ContainerAllocator>
struct set_servoResponse_
{
  typedef set_servoResponse_<ContainerAllocator> Type;

  set_servoResponse_()
    {
    }
  set_servoResponse_(const ContainerAllocator& _alloc)
    {
  (void)_alloc;
    }







  typedef boost::shared_ptr< ::pololu_maestro_ros::set_servoResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::pololu_maestro_ros::set_servoResponse_<ContainerAllocator> const> ConstPtr;

}; // struct set_servoResponse_

typedef ::pololu_maestro_ros::set_servoResponse_<std::allocator<void> > set_servoResponse;

typedef boost::shared_ptr< ::pololu_maestro_ros::set_servoResponse > set_servoResponsePtr;
typedef boost::shared_ptr< ::pololu_maestro_ros::set_servoResponse const> set_servoResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::pololu_maestro_ros::set_servoResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::pololu_maestro_ros::set_servoResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


} // namespace pololu_maestro_ros

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::pololu_maestro_ros::set_servoResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::pololu_maestro_ros::set_servoResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::pololu_maestro_ros::set_servoResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::pololu_maestro_ros::set_servoResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::pololu_maestro_ros::set_servoResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::pololu_maestro_ros::set_servoResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::pololu_maestro_ros::set_servoResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "d41d8cd98f00b204e9800998ecf8427e";
  }

  static const char* value(const ::pololu_maestro_ros::set_servoResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xd41d8cd98f00b204ULL;
  static const uint64_t static_value2 = 0xe9800998ecf8427eULL;
};

template<class ContainerAllocator>
struct DataType< ::pololu_maestro_ros::set_servoResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "pololu_maestro_ros/set_servoResponse";
  }

  static const char* value(const ::pololu_maestro_ros::set_servoResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::pololu_maestro_ros::set_servoResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "\n"
"\n"
;
  }

  static const char* value(const ::pololu_maestro_ros::set_servoResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::pololu_maestro_ros::set_servoResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream&, T)
    {}

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct set_servoResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::pololu_maestro_ros::set_servoResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream&, const std::string&, const ::pololu_maestro_ros::set_servoResponse_<ContainerAllocator>&)
  {}
};

} // namespace message_operations
} // namespace ros

#endif // POLOLU_MAESTRO_ROS_MESSAGE_SET_SERVORESPONSE_H
