(cl:defpackage phidgets_msgs-srv
  (:use )
  (:export
   "SETDIGITALOUTPUT"
   "<SETDIGITALOUTPUT-REQUEST>"
   "SETDIGITALOUTPUT-REQUEST"
   "<SETDIGITALOUTPUT-RESPONSE>"
   "SETDIGITALOUTPUT-RESPONSE"
  ))

