set(_CATKIN_CURRENT_PACKAGE "libphidget21")
set(libphidget21_VERSION "0.7.11")
set(libphidget21_MAINTAINER "Martin Günther <martin.guenther@dfki.de>, Chris Lalancette <clalancette@openrobotics.org>")
set(libphidget21_PACKAGE_FORMAT "2")
set(libphidget21_BUILD_DEPENDS "libusb-1.0-dev")
set(libphidget21_BUILD_EXPORT_DEPENDS )
set(libphidget21_BUILDTOOL_DEPENDS "catkin")
set(libphidget21_BUILDTOOL_EXPORT_DEPENDS )
set(libphidget21_EXEC_DEPENDS "libusb-1.0")
set(libphidget21_RUN_DEPENDS "libusb-1.0")
set(libphidget21_TEST_DEPENDS )
set(libphidget21_DOC_DEPENDS )
set(libphidget21_URL_WEBSITE "http://ros.org/wiki/libphidget21")
set(libphidget21_URL_BUGTRACKER "https://github.com/ros-drivers/phidgets_drivers/issues")
set(libphidget21_URL_REPOSITORY "https://github.com/ros-drivers/phidgets_drivers.git")
set(libphidget21_DEPRECATED "")