set(_CATKIN_CURRENT_PACKAGE "phidgets_high_speed_encoder")
set(phidgets_high_speed_encoder_VERSION "0.7.11")
set(phidgets_high_speed_encoder_MAINTAINER "Martin Günther <martin.guenther@dfki.de>, Chris Lalancette <clalancette@openrobotics.org>")
set(phidgets_high_speed_encoder_PACKAGE_FORMAT "2")
set(phidgets_high_speed_encoder_BUILD_DEPENDS "nodelet" "phidgets_api" "phidgets_msgs" "pluginlib" "roscpp" "sensor_msgs" "std_msgs")
set(phidgets_high_speed_encoder_BUILD_EXPORT_DEPENDS "nodelet" "phidgets_api" "phidgets_msgs" "pluginlib" "roscpp" "sensor_msgs" "std_msgs")
set(phidgets_high_speed_encoder_BUILDTOOL_DEPENDS "catkin")
set(phidgets_high_speed_encoder_BUILDTOOL_EXPORT_DEPENDS )
set(phidgets_high_speed_encoder_EXEC_DEPENDS "nodelet" "phidgets_api" "phidgets_msgs" "pluginlib" "roscpp" "sensor_msgs" "std_msgs")
set(phidgets_high_speed_encoder_RUN_DEPENDS "nodelet" "phidgets_api" "phidgets_msgs" "pluginlib" "roscpp" "sensor_msgs" "std_msgs")
set(phidgets_high_speed_encoder_TEST_DEPENDS )
set(phidgets_high_speed_encoder_DOC_DEPENDS )
set(phidgets_high_speed_encoder_URL_WEBSITE "")
set(phidgets_high_speed_encoder_URL_BUGTRACKER "")
set(phidgets_high_speed_encoder_URL_REPOSITORY "")
set(phidgets_high_speed_encoder_DEPRECATED "")